In [1]:
import numpy as np


In [2]:
np_heights = np.array([[1.60,1.75],[1.56,1.70],[1.49,1.68]])

In [3]:
print (np_heights)

[[1.6  1.75]
 [1.56 1.7 ]
 [1.49 1.68]]


In [4]:
print (np_heights[0][1])

1.75


In [8]:
print (np_heights[:,0])


[1.6  1.56 1.49]


In [9]:
print (np.mean(np_heights[:,0]))

1.55


In [10]:
ls1 = [1,2,3]


In [12]:
ls2 = [4,5,6]

In [13]:
print (ls1 + ls2)

[1, 2, 3, 4, 5, 6]


In [14]:
x = np.array([10, 23, 14, 27])
y = np.array([3, 5, 7, 26])

In [15]:
print(x)

[10 23 14 27]


In [16]:
print(y)

[ 3  5  7 26]


In [22]:
z = np.array([x,y])

In [23]:
print(z.shape)

(2, 4)


In [30]:
p = 1
q = "PradeepPant"

In [31]:
print(q * p)

PradeepPant


In [32]:
x = [1,2,3,4,5]

In [33]:
print(x[1:4])

[2, 3, 4]


In [34]:
p = 2
print (type(p))

<class 'int'>


In [37]:
z = np.array([[1,1,1],[3,4,4]])

In [38]:
z


array([[1, 1, 1],
       [3, 4, 4]])

In [44]:
z[1:,:1]

array([[3]])

In [45]:
z[:,:]

array([[1, 1, 1],
       [3, 4, 4]])

In [46]:
q = [34, 29, 13, 32, 17, 6]

In [47]:
q


[34, 29, 13, 32, 17, 6]

In [50]:
q

[34, 29, 13, 32, 17, 6]

In [54]:
q[-1:]

[6]

In [58]:
len(q)

6